server:
  port: 8090
  servlet:
    context-path: /vhr
  address:

spring:
  profiles:
    active: dev
  application:
    name: vhr
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: root
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小. 是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  # 注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:/mapper/*Dao.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.javaboy.vhr.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.javaboy.vhr.dao: DEBUG
  config: classpath:log4j2.yml # 指定log4j配置文件的位置

swagger:
  enable: true